export interface SyngentaProduct {
  key: string;
  name: string;
  category: 'insecticide' | 'fungicide' | 'herbicide' | 'seed_treatment' | 'biostimulant' | 'pgr';
  activeIngredient: string;
  modeOfAction: string;
  groupCode: string;
  targetPests: string[];
  approvedCrops: string[];
  dosagePerAcre: string;
  waterPerAcre: number;
  applicationTiming: string;
  applicationsPerSeason: string;
  phi: string;
  packSizes: string[];
  mrpInr: string;
  costPerAcre: number;
  efficacyHeat: number;
  efficacyDrought: number;
  efficacyFungal: number;
  efficacyInsect: number;
  efficacyWeed: number;
  efficacySeedborne: number;
  tankMixSafe: string[];
  tankMixDanger: string[];
  stageSuitability: {
    germination: number;
    vegetative: number;
    flowering: number;
    podFormation: number;
    maturity: number;
  };
}

export const syngentaProducts: SyngentaProduct[] = [
  // INSECTICIDES
  {
    key: 'virtako',
    name: 'Virtako',
    category: 'insecticide',
    activeIngredient: 'Thiamethoxam 1% + Chlorantraniliprole 0.5% GR',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'IRAC 4A+28',
    targetPests: ['Stem borer', 'Leaf folder'],
    approvedCrops: ['Rice', 'Maize', 'Sugarcane'],
    dosagePerAcre: '2.5-4 kg',
    waterPerAcre: 0,
    applicationTiming: 'Vegetative',
    applicationsPerSeason: '1-2',
    phi: '21-30',
    packSizes: ['2.5kg'],
    mrpInr: '₹850-900',
    costPerAcre: 900,
    efficacyHeat: 0.1, efficacyDrought: 0.1, efficacyFungal: 0, efficacyInsect: 0.95, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.3, vegetative: 0.95, flowering: 0.6, podFormation: 0.3, maturity: 0.1 }
  },
  {
    key: 'ampligo',
    name: 'Ampligo',
    category: 'insecticide',
    activeIngredient: 'Chlorantraniliprole 10% + Lambda-cyhalothrin 5% ZC',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'IRAC 28+3A',
    targetPests: ['Bollworms', 'Stem borer'],
    approvedCrops: ['Cotton', 'Rice', 'Redgram'],
    dosagePerAcre: '80-100ml',
    waterPerAcre: 200,
    applicationTiming: 'Flowering/Pod',
    applicationsPerSeason: '1-2',
    phi: '15-20',
    packSizes: ['100ml'],
    mrpInr: '₹800-900',
    costPerAcre: 850,
    efficacyHeat: 0.1, efficacyDrought: 0.1, efficacyFungal: 0, efficacyInsect: 0.95, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.5, flowering: 0.95, podFormation: 0.9, maturity: 0.3 }
  },
  {
    key: 'alika',
    name: 'Alika',
    category: 'insecticide',
    activeIngredient: 'Thiamethoxam 12.6% + Lambda-cyhalothrin 9.5% ZC',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'IRAC 4A+3A',
    targetPests: ['Aphids', 'Jassids', 'Thrips', 'Whitefly', 'Bollworms'],
    approvedCrops: ['Cotton', 'Groundnut', 'Tomato'],
    dosagePerAcre: '80ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg/Flowering',
    applicationsPerSeason: '1-2',
    phi: '21',
    packSizes: ['80ml'],
    mrpInr: '₹550',
    costPerAcre: 550,
    efficacyHeat: 0.1, efficacyDrought: 0.05, efficacyFungal: 0, efficacyInsect: 0.92, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.9, flowering: 0.85, podFormation: 0.5, maturity: 0.2 }
  },
  {
    key: 'chess',
    name: 'Chess',
    category: 'insecticide',
    activeIngredient: 'Pymetrozine 50% WG',
    modeOfAction: 'Systemic',
    groupCode: 'IRAC 9B',
    targetPests: ['BPH', 'WBPH', 'Hoppers'],
    approvedCrops: ['Rice'],
    dosagePerAcre: '120g',
    waterPerAcre: 200,
    applicationTiming: 'Tillering to panicle',
    applicationsPerSeason: '1-2',
    phi: '19',
    packSizes: ['120g'],
    mrpInr: '₹700',
    costPerAcre: 700,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.90, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.95, flowering: 0.7, podFormation: 0.4, maturity: 0.1 }
  },
  {
    key: 'pegasus',
    name: 'Pegasus',
    category: 'insecticide',
    activeIngredient: 'Diafenthiuron 50% WP',
    modeOfAction: 'Contact + Stomach + Translaminar',
    groupCode: 'IRAC 12A',
    targetPests: ['Whiteflies', 'Aphids', 'Mites', 'DBM'],
    approvedCrops: ['Cotton', 'Chilli', 'Cabbage'],
    dosagePerAcre: '250g',
    waterPerAcre: 200,
    applicationTiming: 'Veg/early fruiting',
    applicationsPerSeason: '1-2',
    phi: '7-10',
    packSizes: ['250g'],
    mrpInr: '₹600',
    costPerAcre: 600,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0, efficacyInsect: 0.88, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.9, flowering: 0.7, podFormation: 0.5, maturity: 0.2 }
  },
  {
    key: 'actara',
    name: 'Actara',
    category: 'insecticide',
    activeIngredient: 'Thiamethoxam 25% WG',
    modeOfAction: 'Systemic',
    groupCode: 'IRAC 4A',
    targetPests: ['Aphids', 'Jassids', 'Hoppers'],
    approvedCrops: ['Rice', 'Cotton', 'Vegetables'],
    dosagePerAcre: '40-80g',
    waterPerAcre: 200,
    applicationTiming: 'Early veg',
    applicationsPerSeason: '1-2',
    phi: '14-21',
    packSizes: ['100g'],
    mrpInr: '₹250',
    costPerAcre: 250,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0, efficacyInsect: 0.88, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.3, vegetative: 0.95, flowering: 0.6, podFormation: 0.3, maturity: 0.1 }
  },
  {
    key: 'simodis',
    name: 'Simodis',
    category: 'insecticide',
    activeIngredient: 'Isocycloseram 9.2% DC',
    modeOfAction: 'Contact + Ingestion',
    groupCode: 'IRAC 30',
    targetPests: ['Thrips', 'Mites', 'DBM'],
    approvedCrops: ['Chilli', 'Cabbage'],
    dosagePerAcre: '240-300ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg/flowering',
    applicationsPerSeason: '1-2',
    phi: '7-10',
    packSizes: ['100ml'],
    mrpInr: '₹900',
    costPerAcre: 2200,
    efficacyHeat: 0.05, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.93, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.85, flowering: 0.9, podFormation: 0.5, maturity: 0.2 }
  },
  {
    key: 'evicent',
    name: 'Evicent',
    category: 'insecticide',
    activeIngredient: 'Emamectin benzoate 5% SG',
    modeOfAction: 'Contact + Translaminar',
    groupCode: 'IRAC 6',
    targetPests: ['Bollworms', 'Fruit borers', 'Caterpillars'],
    approvedCrops: ['Cotton', 'Chilli', 'Pigeon pea'],
    dosagePerAcre: '80g',
    waterPerAcre: 200,
    applicationTiming: 'Flowering/Fruiting',
    applicationsPerSeason: '1-2',
    phi: '7-14',
    packSizes: ['100g'],
    mrpInr: '₹450',
    costPerAcre: 360,
    efficacyHeat: 0.05, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.90, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.05, vegetative: 0.4, flowering: 0.95, podFormation: 0.85, maturity: 0.3 }
  },
  {
    key: 'minecto_xtra',
    name: 'Minecto Xtra',
    category: 'insecticide',
    activeIngredient: 'Cyantraniliprole + Lufenuron SC',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'IRAC 28+15',
    targetPests: ['DBM', 'Spodoptera', 'Fruit borers'],
    approvedCrops: ['Cabbage', 'Chilli', 'Cotton'],
    dosagePerAcre: '150-200ml',
    waterPerAcre: 200,
    applicationTiming: 'Fruiting',
    applicationsPerSeason: '1',
    phi: '14',
    packSizes: ['100ml'],
    mrpInr: '₹1200',
    costPerAcre: 2400,
    efficacyHeat: 0.05, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.94, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.05, vegetative: 0.5, flowering: 0.85, podFormation: 0.95, maturity: 0.3 }
  },
  {
    key: 'voliam_flexi',
    name: 'Voliam Flexi',
    category: 'insecticide',
    activeIngredient: 'Thiamethoxam 17.5% + Chlorantraniliprole 8.8% SC',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'IRAC 4A+28',
    targetPests: ['Fruit borers', 'Stem borer', 'Whitefly'],
    approvedCrops: ['Tomato', 'Rice'],
    dosagePerAcre: '80-100ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg/early fruiting',
    applicationsPerSeason: '1-2',
    phi: '14',
    packSizes: ['100ml'],
    mrpInr: '₹950',
    costPerAcre: 950,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0, efficacyInsect: 0.93, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.90, flowering: 0.80, podFormation: 0.6, maturity: 0.2 }
  },
  {
    key: 'matador',
    name: 'Matador',
    category: 'insecticide',
    activeIngredient: 'Lambda-cyhalothrin 5% EC',
    modeOfAction: 'Contact + Stomach',
    groupCode: 'IRAC 3A',
    targetPests: ['Bollworms', 'Stem borer', 'Thrips'],
    approvedCrops: ['Cotton', 'Paddy', 'Vegetables'],
    dosagePerAcre: '200-250ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg/Flowering',
    applicationsPerSeason: '1-3',
    phi: '10-15',
    packSizes: ['500ml'],
    mrpInr: '₹400',
    costPerAcre: 200,
    efficacyHeat: 0.05, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.80, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.85, flowering: 0.75, podFormation: 0.5, maturity: 0.2 }
  },
  {
    key: 'karate',
    name: 'Karate',
    category: 'insecticide',
    activeIngredient: 'Lambda-cyhalothrin 2.5% EC',
    modeOfAction: 'Contact + Stomach',
    groupCode: 'IRAC 3A',
    targetPests: ['Bollworms', 'Jassids', 'Thrips'],
    approvedCrops: ['Cotton', 'Vegetables'],
    dosagePerAcre: '300-400ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg',
    applicationsPerSeason: '1-3',
    phi: '10-15',
    packSizes: ['500ml'],
    mrpInr: '₹300',
    costPerAcre: 200,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.78, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.9, flowering: 0.6, podFormation: 0.4, maturity: 0.15 }
  },
  {
    key: 'polytrin_c',
    name: 'Polytrin C',
    category: 'insecticide',
    activeIngredient: 'Profenofos 40% + Cypermethrin 4% EC',
    modeOfAction: 'Contact + Stomach',
    groupCode: 'IRAC 1B+3A',
    targetPests: ['Bollworms', 'Whitefly'],
    approvedCrops: ['Cotton'],
    dosagePerAcre: '400-600ml',
    waterPerAcre: 200,
    applicationTiming: 'Flowering/Boll',
    applicationsPerSeason: '2',
    phi: '14',
    packSizes: ['1L'],
    mrpInr: '₹650',
    costPerAcre: 350,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.82, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.05, vegetative: 0.5, flowering: 0.9, podFormation: 0.85, maturity: 0.2 }
  },
  {
    key: 'curacron',
    name: 'Curacron',
    category: 'insecticide',
    activeIngredient: 'Profenofos 50% EC',
    modeOfAction: 'Contact + Stomach + Translaminar',
    groupCode: 'IRAC 1B',
    targetPests: ['Spodoptera', 'Bollworms', 'Mealybugs'],
    approvedCrops: ['Cotton', 'Soybean'],
    dosagePerAcre: '400-500ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg/Flowering',
    applicationsPerSeason: '2',
    phi: '14',
    packSizes: ['1L'],
    mrpInr: '₹700',
    costPerAcre: 350,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.82, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.85, flowering: 0.8, podFormation: 0.5, maturity: 0.15 }
  },
  {
    key: 'ekalux',
    name: 'Ekalux',
    category: 'insecticide',
    activeIngredient: 'Quinalphos 25% EC',
    modeOfAction: 'Contact + Stomach + Penetrant',
    groupCode: 'IRAC 1B',
    targetPests: ['Stem borer', 'Leaf folder'],
    approvedCrops: ['Rice', 'Cotton'],
    dosagePerAcre: '400-500ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg',
    applicationsPerSeason: '2',
    phi: '21',
    packSizes: ['1L'],
    mrpInr: '₹600',
    costPerAcre: 300,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.78, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.9, flowering: 0.5, podFormation: 0.3, maturity: 0.1 }
  },
  {
    key: 'polo',
    name: 'Polo',
    category: 'insecticide',
    activeIngredient: 'Diafenthiuron 50% WP',
    modeOfAction: 'Contact + Stomach + Translaminar',
    groupCode: 'IRAC 12A',
    targetPests: ['Whiteflies', 'Aphids', 'Mites'],
    approvedCrops: ['Cotton', 'Chilli', 'Brinjal'],
    dosagePerAcre: '250g',
    waterPerAcre: 200,
    applicationTiming: 'Early infestation',
    applicationsPerSeason: '1-2',
    phi: '7',
    packSizes: ['250g'],
    mrpInr: '₹650',
    costPerAcre: 650,
    efficacyHeat: 0.05, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0.87, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.9, flowering: 0.7, podFormation: 0.4, maturity: 0.15 }
  },

  // FUNGICIDES
  {
    key: 'amistar_top',
    name: 'Amistar Top',
    category: 'fungicide',
    activeIngredient: 'Azoxystrobin 18.2% + Difenoconazole 11.4% SC',
    modeOfAction: 'Systemic + Translaminar',
    groupCode: 'FRAC 11+3',
    targetPests: ['Blast', 'Blights', 'Rust', 'Mildew'],
    approvedCrops: ['Paddy', 'Wheat', 'Maize', 'Chilli', 'Tomato'],
    dosagePerAcre: '200ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive/early onset',
    applicationsPerSeason: '1-2',
    phi: '14-21',
    packSizes: ['200ml'],
    mrpInr: '₹1300',
    costPerAcre: 1300,
    efficacyHeat: 0.15, efficacyDrought: 0.1, efficacyFungal: 0.95, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0.1,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.7, flowering: 0.95, podFormation: 0.85, maturity: 0.4 }
  },
  {
    key: 'score',
    name: 'Score',
    category: 'fungicide',
    activeIngredient: 'Difenoconazole 25% EC',
    modeOfAction: 'Systemic',
    groupCode: 'FRAC 3',
    targetPests: ['Scab', 'Early Blight', 'Sheath blight'],
    approvedCrops: ['Apple', 'Tomato', 'Rice'],
    dosagePerAcre: '100ml',
    waterPerAcre: 200,
    applicationTiming: 'Disease onset',
    applicationsPerSeason: '1-3',
    phi: '14',
    packSizes: ['250ml'],
    mrpInr: '₹750',
    costPerAcre: 300,
    efficacyHeat: 0.1, efficacyDrought: 0.05, efficacyFungal: 0.90, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.15, vegetative: 0.6, flowering: 0.90, podFormation: 0.8, maturity: 0.4 }
  },
  {
    key: 'kavach',
    name: 'Kavach',
    category: 'fungicide',
    activeIngredient: 'Chlorothalonil 720g/l SC',
    modeOfAction: 'Contact / Multi-site',
    groupCode: 'FRAC M5',
    targetPests: ['Late blight', 'Early blight', 'Downy mildew'],
    approvedCrops: ['Potato', 'Tomato', 'Grapes'],
    dosagePerAcre: '400ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive',
    applicationsPerSeason: '1-3',
    phi: '7-14',
    packSizes: ['500ml'],
    mrpInr: '₹800',
    costPerAcre: 640,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.85, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.85, flowering: 0.8, podFormation: 0.7, maturity: 0.3 }
  },
  {
    key: 'orondis_ultra',
    name: 'Orondis Ultra',
    category: 'fungicide',
    activeIngredient: 'Oxathiapiprolin + Mandipropamid SC',
    modeOfAction: 'Systemic + Translaminar',
    groupCode: 'FRAC 49+40',
    targetPests: ['Late Blight', 'Downy Mildew'],
    approvedCrops: ['Potato', 'Grapes', 'Tomato'],
    dosagePerAcre: '200ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive',
    applicationsPerSeason: '1-2',
    phi: '3-7',
    packSizes: ['200ml'],
    mrpInr: '₹1100',
    costPerAcre: 1100,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.96, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.3, vegetative: 0.85, flowering: 0.90, podFormation: 0.8, maturity: 0.4 }
  },
  {
    key: 'ridomil_gold',
    name: 'Ridomil Gold',
    category: 'fungicide',
    activeIngredient: 'Metalaxyl-M 4% + Mancozeb 64% WP',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'FRAC 4+M3',
    targetPests: ['Late Blight', 'Downy Mildew'],
    approvedCrops: ['Potato', 'Grapes', 'Tobacco'],
    dosagePerAcre: '500-1000g',
    waterPerAcre: 200,
    applicationTiming: 'Preventive/Curative',
    applicationsPerSeason: '1-3',
    phi: '7-14',
    packSizes: ['500g'],
    mrpInr: '₹1000',
    costPerAcre: 1000,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.92, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0.15,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.3, vegetative: 0.85, flowering: 0.85, podFormation: 0.7, maturity: 0.3 }
  },
  {
    key: 'ampect_xtra',
    name: 'Ampect Xtra',
    category: 'fungicide',
    activeIngredient: 'Azoxystrobin 18.2% + Cyproconazole 7.3% SC',
    modeOfAction: 'Systemic + Translaminar',
    groupCode: 'FRAC 11+3',
    targetPests: ['Rust', 'Smut', 'Leaf Spots'],
    approvedCrops: ['Sugarcane', 'Wheat'],
    dosagePerAcre: '200ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive/Curative',
    applicationsPerSeason: '1-2',
    phi: '21',
    packSizes: ['200ml'],
    mrpInr: '₹1000',
    costPerAcre: 1000,
    efficacyHeat: 0.1, efficacyDrought: 0.05, efficacyFungal: 0.90, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.15, vegetative: 0.8, flowering: 0.85, podFormation: 0.7, maturity: 0.35 }
  },
  {
    key: 'folio_gold',
    name: 'Folio Gold',
    category: 'fungicide',
    activeIngredient: 'Metalaxyl-M 3.3% + Chlorothalonil 33.1% SC',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'FRAC 4+M5',
    targetPests: ['Late Blight', 'Downy mildew'],
    approvedCrops: ['Potato', 'Tomato', 'Onion'],
    dosagePerAcre: '400ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive',
    applicationsPerSeason: '1-2',
    phi: '14',
    packSizes: ['500ml'],
    mrpInr: '₹850',
    costPerAcre: 680,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.88, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.25, vegetative: 0.85, flowering: 0.8, podFormation: 0.7, maturity: 0.3 }
  },
  {
    key: 'tilt',
    name: 'Tilt',
    category: 'fungicide',
    activeIngredient: 'Propiconazole 25% EC',
    modeOfAction: 'Systemic',
    groupCode: 'FRAC 3',
    targetPests: ['Rust', 'Karnal bunt', 'Sheath blight'],
    approvedCrops: ['Wheat', 'Rice', 'Groundnut'],
    dosagePerAcre: '200ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive/Curative',
    applicationsPerSeason: '1-2',
    phi: '14-21',
    packSizes: ['500ml'],
    mrpInr: '₹550',
    costPerAcre: 220,
    efficacyHeat: 0.1, efficacyDrought: 0.05, efficacyFungal: 0.85, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.15, vegetative: 0.7, flowering: 0.85, podFormation: 0.7, maturity: 0.35 }
  },
  {
    key: 'bravo',
    name: 'Bravo',
    category: 'fungicide',
    activeIngredient: 'Chlorothalonil 75% WP',
    modeOfAction: 'Contact / Multi-site',
    groupCode: 'FRAC M5',
    targetPests: ['Early Blight', 'Late blight', 'Anthracnose'],
    approvedCrops: ['Grapes', 'Potato', 'Vegetables'],
    dosagePerAcre: '400g',
    waterPerAcre: 200,
    applicationTiming: 'Preventive',
    applicationsPerSeason: '1-3',
    phi: '7-14',
    packSizes: ['500g'],
    mrpInr: '₹650',
    costPerAcre: 520,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.83, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.8, flowering: 0.75, podFormation: 0.65, maturity: 0.3 }
  },
  {
    key: 'splash',
    name: 'Splash',
    category: 'fungicide',
    activeIngredient: 'Fludioxonil 20% WG',
    modeOfAction: 'Contact',
    groupCode: 'FRAC 12',
    targetPests: ['Botrytis', 'Anthracnose'],
    approvedCrops: ['Grapes', 'Mango'],
    dosagePerAcre: '100-150g',
    waterPerAcre: 200,
    applicationTiming: 'Fruiting',
    applicationsPerSeason: '1-2',
    phi: '7',
    packSizes: ['100g'],
    mrpInr: '₹800',
    costPerAcre: 1000,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.85, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.3, flowering: 0.7, podFormation: 0.95, maturity: 0.6 }
  },
  {
    key: 'amistar',
    name: 'Amistar',
    category: 'fungicide',
    activeIngredient: 'Azoxystrobin 23% SC',
    modeOfAction: 'Systemic + Translaminar',
    groupCode: 'FRAC 11',
    targetPests: ['Downy mildew', 'Powdery mildew', 'Anthracnose'],
    approvedCrops: ['Grapes', 'Mango', 'Chilli'],
    dosagePerAcre: '200ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive',
    applicationsPerSeason: '1-2',
    phi: '7-14',
    packSizes: ['200ml'],
    mrpInr: '₹1400',
    costPerAcre: 1400,
    efficacyHeat: 0.1, efficacyDrought: 0.05, efficacyFungal: 0.90, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.15, vegetative: 0.7, flowering: 0.90, podFormation: 0.8, maturity: 0.4 }
  },
  {
    key: 'revus',
    name: 'Revus',
    category: 'fungicide',
    activeIngredient: 'Mandipropamid 23.4% SC',
    modeOfAction: 'Translaminar',
    groupCode: 'FRAC 40',
    targetPests: ['Late Blight', 'Downy Mildew'],
    approvedCrops: ['Potato', 'Grapes', 'Tomato'],
    dosagePerAcre: '160-200ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive',
    applicationsPerSeason: '1-2',
    phi: '3-5',
    packSizes: ['250ml'],
    mrpInr: '₹800',
    costPerAcre: 640,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.88, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.85, flowering: 0.85, podFormation: 0.75, maturity: 0.35 }
  },
  {
    key: 'priori_top',
    name: 'Priori Top',
    category: 'fungicide',
    activeIngredient: 'Azoxystrobin + Difenoconazole',
    modeOfAction: 'Systemic + Translaminar',
    groupCode: 'FRAC 11+3',
    targetPests: ['Blast', 'Sheath Blight'],
    approvedCrops: ['Rice'],
    dosagePerAcre: '200ml',
    waterPerAcre: 200,
    applicationTiming: 'Preventive/Curative',
    applicationsPerSeason: '1-2',
    phi: '14',
    packSizes: ['200ml'],
    mrpInr: '₹1300',
    costPerAcre: 1300,
    efficacyHeat: 0.1, efficacyDrought: 0.05, efficacyFungal: 0.93, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.15, vegetative: 0.7, flowering: 0.90, podFormation: 0.8, maturity: 0.4 }
  },
  {
    key: 'unix',
    name: 'Unix',
    category: 'fungicide',
    activeIngredient: 'Cyprodinil 75% WG',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'FRAC 9',
    targetPests: ['Botrytis', 'Scab'],
    approvedCrops: ['Grapes', 'Apple'],
    dosagePerAcre: '200g',
    waterPerAcre: 200,
    applicationTiming: 'Preventive',
    applicationsPerSeason: '1-2',
    phi: '7-14',
    packSizes: ['250g'],
    mrpInr: '₹1100',
    costPerAcre: 880,
    efficacyHeat: 0.05, efficacyDrought: 0.05, efficacyFungal: 0.85, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.1, vegetative: 0.5, flowering: 0.85, podFormation: 0.8, maturity: 0.5 }
  },
  {
    key: 'dividend',
    name: 'Dividend',
    category: 'seed_treatment',
    activeIngredient: 'Difenoconazole 3% FS',
    modeOfAction: 'Systemic',
    groupCode: 'FRAC 3',
    targetPests: ['Karnal Bunt', 'Loose Smut'],
    approvedCrops: ['Wheat'],
    dosagePerAcre: '2ml/kg seed',
    waterPerAcre: 0,
    applicationTiming: 'Pre-sowing',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['100ml'],
    mrpInr: '₹250',
    costPerAcre: 150,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0.80, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0.90,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.1, flowering: 0, podFormation: 0, maturity: 0 }
  },

  // HERBICIDES
  {
    key: 'calaris_xtra',
    name: 'Calaris Xtra',
    category: 'herbicide',
    activeIngredient: 'Mesotrione 2.27% + Atrazine 22.7% SC',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC F2+C1',
    targetPests: ['Broadleaf+Grassy weeds'],
    approvedCrops: ['Maize', 'Sugarcane'],
    dosagePerAcre: '1400ml',
    waterPerAcre: 200,
    applicationTiming: 'Post-emergence 3-4 leaf',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['700ml'],
    mrpInr: '₹1450',
    costPerAcre: 2900,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.92, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.3, vegetative: 0.95, flowering: 0.2, podFormation: 0.05, maturity: 0 }
  },
  {
    key: 'axial',
    name: 'Axial',
    category: 'herbicide',
    activeIngredient: 'Pinoxaden 5.1% EC',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC A',
    targetPests: ['Phalaris minor'],
    approvedCrops: ['Wheat'],
    dosagePerAcre: '400ml',
    waterPerAcre: 200,
    applicationTiming: 'Post-emergence',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['400ml'],
    mrpInr: '₹750',
    costPerAcre: 750,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.90, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.95, flowering: 0.1, podFormation: 0, maturity: 0 }
  },
  {
    key: 'topik',
    name: 'Topik',
    category: 'herbicide',
    activeIngredient: 'Clodinafop-propargyl 15% WP',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC A',
    targetPests: ['Phalaris minor'],
    approvedCrops: ['Wheat'],
    dosagePerAcre: '160g',
    waterPerAcre: 150,
    applicationTiming: 'Post-emergence 35 DAS',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['160g'],
    mrpInr: '₹450',
    costPerAcre: 450,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.88, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.95, flowering: 0.1, podFormation: 0, maturity: 0 }
  },
  {
    key: 'rifit_plus',
    name: 'Rifit Plus',
    category: 'herbicide',
    activeIngredient: 'Pretilachlor 37% EW',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC K3',
    targetPests: ['Annual grasses', 'sedges', 'broadleaf'],
    approvedCrops: ['Rice(Transplanted)', 'Rice'],
    dosagePerAcre: '600ml',
    waterPerAcre: 0,
    applicationTiming: 'Pre-emergence 0-3 DAT',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['600ml'],
    mrpInr: '₹450',
    costPerAcre: 450,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.88, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.3, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'fusiflex',
    name: 'Fusiflex',
    category: 'herbicide',
    activeIngredient: 'Fluazifop-p-butyl 13.4% + Fomesafen 11.1% SL',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC A+E',
    targetPests: ['Grasses+broadleaf'],
    approvedCrops: ['Soybean', 'Groundnut'],
    dosagePerAcre: '400ml',
    waterPerAcre: 200,
    applicationTiming: 'Post-emergence',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['400ml'],
    mrpInr: '₹950',
    costPerAcre: 950,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.90, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.95, flowering: 0.1, podFormation: 0, maturity: 0 }
  },
  {
    key: 'gramoxone',
    name: 'Gramoxone',
    category: 'herbicide',
    activeIngredient: 'Paraquat dichloride 24% SL',
    modeOfAction: 'Contact',
    groupCode: 'HRAC D',
    targetPests: ['All emerged weeds'],
    approvedCrops: ['Non-crop', 'Plantation'],
    dosagePerAcre: '500-1000ml',
    waterPerAcre: 200,
    applicationTiming: 'Post-emergence weeds',
    applicationsPerSeason: '1-2',
    phi: 'N/A',
    packSizes: ['1L'],
    mrpInr: '₹400',
    costPerAcre: 300,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.85, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.5, vegetative: 0.3, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'touchdown',
    name: 'Touchdown',
    category: 'herbicide',
    activeIngredient: 'Glyphosate ammonium salt 5% SL',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC G',
    targetPests: ['Annual+perennial weeds'],
    approvedCrops: ['Non-crop', 'Tea'],
    dosagePerAcre: '1L',
    waterPerAcre: 200,
    applicationTiming: 'Active weed growth',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['1L'],
    mrpInr: '₹600',
    costPerAcre: 600,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.88, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.5, vegetative: 0.3, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'dual_gold',
    name: 'Dual Gold',
    category: 'herbicide',
    activeIngredient: 'S-metolachlor 960g/l EC',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC K3',
    targetPests: ['Grasses+broadleaf'],
    approvedCrops: ['Maize', 'Soybean'],
    dosagePerAcre: '400-500ml',
    waterPerAcre: 200,
    applicationTiming: 'Pre-emergence',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['500ml'],
    mrpInr: '₹800',
    costPerAcre: 720,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.87, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.3, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'lumax',
    name: 'Lumax',
    category: 'herbicide',
    activeIngredient: 'Mesotrione + S-metolachlor + Atrazine',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC F2+K3+C1',
    targetPests: ['Broadleaf+grasses'],
    approvedCrops: ['Maize'],
    dosagePerAcre: '1400ml',
    waterPerAcre: 200,
    applicationTiming: 'Pre/Early Post',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['1L'],
    mrpInr: '₹1500',
    costPerAcre: 2100,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.93, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.8, vegetative: 0.95, flowering: 0.1, podFormation: 0, maturity: 0 }
  },
  {
    key: 'gesaprim',
    name: 'Gesaprim',
    category: 'herbicide',
    activeIngredient: 'Atrazine 50% WP',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC C1',
    targetPests: ['Broadleaf weeds'],
    approvedCrops: ['Maize', 'Sugarcane'],
    dosagePerAcre: '400-800g',
    waterPerAcre: 200,
    applicationTiming: 'Pre/early post',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['500g'],
    mrpInr: '₹350',
    costPerAcre: 420,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.82, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.8, vegetative: 0.85, flowering: 0.1, podFormation: 0, maturity: 0 }
  },
  {
    key: 'bicep',
    name: 'Bicep',
    category: 'herbicide',
    activeIngredient: 'Atrazine + S-metolachlor',
    modeOfAction: 'Systemic',
    groupCode: 'HRAC C1+K3',
    targetPests: ['Grasses+broadleaf'],
    approvedCrops: ['Maize', 'Sugarcane'],
    dosagePerAcre: '1L',
    waterPerAcre: 200,
    applicationTiming: 'Pre-emergence',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['1L'],
    mrpInr: '₹800',
    costPerAcre: 800,
    efficacyHeat: 0, efficacyDrought: 0, efficacyFungal: 0, efficacyInsect: 0, efficacyWeed: 0.88, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.9, vegetative: 0.5, flowering: 0.05, podFormation: 0, maturity: 0 }
  },

  // SEED TREATMENTS
  {
    key: 'fortenza_duo',
    name: 'Fortenza Duo',
    category: 'seed_treatment',
    activeIngredient: 'Cyantraniliprole + Thiamethoxam FS',
    modeOfAction: 'Systemic',
    groupCode: 'IRAC 28+4A',
    targetPests: ['Early pests', 'Cutworms', 'Stem borer'],
    approvedCrops: ['Maize', 'Cotton'],
    dosagePerAcre: '4-6ml/kg seed',
    waterPerAcre: 0,
    applicationTiming: 'Pre-sowing',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['100ml'],
    mrpInr: '₹600',
    costPerAcre: 300,
    efficacyHeat: 0, efficacyDrought: 0.1, efficacyFungal: 0, efficacyInsect: 0.85, efficacyWeed: 0, efficacySeedborne: 0.3,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.3, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'cruiser',
    name: 'Cruiser',
    category: 'seed_treatment',
    activeIngredient: 'Thiamethoxam 30% FS',
    modeOfAction: 'Systemic',
    groupCode: 'IRAC 4A',
    targetPests: ['Jassids', 'Aphids', 'Whitefly'],
    approvedCrops: ['Cotton', 'Soybean', 'Maize'],
    dosagePerAcre: '3-5ml/kg seed',
    waterPerAcre: 0,
    applicationTiming: 'Pre-sowing',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['100ml'],
    mrpInr: '₹450',
    costPerAcre: 200,
    efficacyHeat: 0, efficacyDrought: 0.05, efficacyFungal: 0, efficacyInsect: 0.82, efficacyWeed: 0, efficacySeedborne: 0.2,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.2, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'vibrance_premium',
    name: 'Vibrance Premium',
    category: 'seed_treatment',
    activeIngredient: 'Sedaxane + Fludioxonil + Metalaxyl-M FS',
    modeOfAction: 'Systemic + Contact',
    groupCode: 'FRAC 7+12+4',
    targetPests: ['Seed/soil-borne diseases'],
    approvedCrops: ['Wheat', 'Soybean'],
    dosagePerAcre: '2-3ml/kg seed',
    waterPerAcre: 0,
    applicationTiming: 'Pre-sowing',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['100ml'],
    mrpInr: '₹500',
    costPerAcre: 200,
    efficacyHeat: 0, efficacyDrought: 0.1, efficacyFungal: 0.7, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0.95,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.15, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'maxim',
    name: 'Maxim',
    category: 'seed_treatment',
    activeIngredient: 'Fludioxonil 480g/l FS',
    modeOfAction: 'Contact',
    groupCode: 'FRAC 12',
    targetPests: ['Seed-borne diseases'],
    approvedCrops: ['Soybean', 'Cotton'],
    dosagePerAcre: '2ml/kg seed',
    waterPerAcre: 0,
    applicationTiming: 'Pre-sowing',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['100ml'],
    mrpInr: '₹350',
    costPerAcre: 150,
    efficacyHeat: 0, efficacyDrought: 0.05, efficacyFungal: 0.5, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0.90,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.1, flowering: 0, podFormation: 0, maturity: 0 }
  },
  {
    key: 'apron_xl',
    name: 'Apron XL',
    category: 'seed_treatment',
    activeIngredient: 'Metalaxyl-M 35% WS',
    modeOfAction: 'Systemic',
    groupCode: 'FRAC 4',
    targetPests: ['Downy mildew', 'Damping off'],
    approvedCrops: ['Maize', 'Sunflower'],
    dosagePerAcre: '2.5g/kg seed',
    waterPerAcre: 0,
    applicationTiming: 'Pre-sowing',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['100g'],
    mrpInr: '₹300',
    costPerAcre: 120,
    efficacyHeat: 0, efficacyDrought: 0.05, efficacyFungal: 0.6, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0.88,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.95, vegetative: 0.15, flowering: 0, podFormation: 0, maturity: 0 }
  },

  // BIOSTIMULANTS & PGR
  {
    key: 'isabion',
    name: 'Isabion',
    category: 'biostimulant',
    activeIngredient: 'Amino acids + Peptides',
    modeOfAction: 'Systemic biostimulant',
    groupCode: 'N/A',
    targetPests: ['Stress relief', 'Growth', 'Yield'],
    approvedCrops: ['All crops'],
    dosagePerAcre: '400ml',
    waterPerAcre: 200,
    applicationTiming: 'Veg/Flowering/Fruiting',
    applicationsPerSeason: '2-3',
    phi: 'N/A',
    packSizes: ['500ml'],
    mrpInr: '₹500',
    costPerAcre: 400,
    efficacyHeat: 0.85, efficacyDrought: 0.70, efficacyFungal: 0.15, efficacyInsect: 0.05, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.3, vegetative: 0.85, flowering: 0.95, podFormation: 0.80, maturity: 0.3 }
  },
  {
    key: 'quantis',
    name: 'Quantis',
    category: 'biostimulant',
    activeIngredient: 'Amino acids + Potassium + Calcium',
    modeOfAction: 'Systemic biostimulant',
    groupCode: 'N/A',
    targetPests: ['Drought/heat stress', 'yield'],
    approvedCrops: ['Potato', 'Soybean', 'Wheat'],
    dosagePerAcre: '400ml',
    waterPerAcre: 200,
    applicationTiming: 'Pre-flowering/Stress',
    applicationsPerSeason: '2',
    phi: 'N/A',
    packSizes: ['1L'],
    mrpInr: '₹600',
    costPerAcre: 300,
    efficacyHeat: 0.90, efficacyDrought: 0.88, efficacyFungal: 0.10, efficacyInsect: 0.05, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0.2, vegetative: 0.80, flowering: 0.92, podFormation: 0.75, maturity: 0.25 }
  },
  {
    key: 'cultar',
    name: 'Cultar',
    category: 'pgr',
    activeIngredient: 'Paclobutrazol 23% SC',
    modeOfAction: 'Systemic PGR',
    groupCode: 'N/A',
    targetPests: ['Vegetative growth regulation', 'flowering promotion'],
    approvedCrops: ['Mango', 'Onion'],
    dosagePerAcre: 'drench (tree age dependent)',
    waterPerAcre: 0,
    applicationTiming: 'Pre-flowering soil drench',
    applicationsPerSeason: '1',
    phi: 'N/A',
    packSizes: ['1L'],
    mrpInr: '₹1600',
    costPerAcre: 2000,
    efficacyHeat: 0.20, efficacyDrought: 0.15, efficacyFungal: 0.05, efficacyInsect: 0, efficacyWeed: 0, efficacySeedborne: 0,
    tankMixSafe: [], tankMixDanger: [],
    stageSuitability: { germination: 0, vegetative: 0.9, flowering: 0.95, podFormation: 0.3, maturity: 0.1 }
  }
];

export function getAllProducts(): SyngentaProduct[] {
  return syngentaProducts;
}

export function getProductByKey(key: string): SyngentaProduct | undefined {
  return syngentaProducts.find(p => p.key === key);
}

export function getProductsByCategory(category: string): SyngentaProduct[] {
  return syngentaProducts.filter(p => p.category === category);
}

export function getProductsForCrop(cropName: string): SyngentaProduct[] {
  const lowerCrop = cropName.toLowerCase();
  return syngentaProducts.filter(p => 
    p.approvedCrops.some(c => c.toLowerCase().includes(lowerCrop))
  );
}

export function getProductsForStage(stage: string): SyngentaProduct[] {
  return syngentaProducts.filter(p => {
    const score = (p.stageSuitability as any)[stage];
    return typeof score === 'number' && score > 0.5;
  });
}
